spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost}/asset-service
  application:
    name: asset-service
  cloud:
    stream:
      bindings:
        rentalDeals:
          destination: rentalDeals
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true